# -*- coding: utf-8 -*-
"""Ploteo_EMG_BITalino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dk7GaryxeKmt_OQCDY01dGV_gR8zA8Ub

# Ploteo de señales EMG en Python

Este notebook permite visualizar las señales EMG adquiridas con BITalino y exportadas desde OpenSignals.

**Archivos analizados:**
- `biceps kevin.txt`
- `triceps kevin.txt`
- `triceps leo.txt`

Las tres adquisiciones fueron realizadas en el canal **A1** con una frecuencia de muestreo de **1000 Hz**.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

"""## 1. Cargar los archivos

Ejecuta la siguiente celda y selecciona los tres archivos `.txt` exportados desde OpenSignals.
"""

uploaded = files.upload()

"""## 2. Función para leer una señal OpenSignals

Los archivos contienen tres líneas de cabecera. La señal EMG registrada en A1 se encuentra en la sexta columna.
"""

def cargar_emg(nombre_archivo):
    datos = pd.read_csv(
        nombre_archivo,
        sep='\\t',
        comment='#',
        header=None
    )

    # Canal analógico A1: sexta columna del archivo OpenSignals
    emg = datos.iloc[:, 5].dropna().to_numpy(dtype=float)
    return emg

fs = 1000  # Hz

"""## 3. Función de ploteo

Para facilitar la visualización se elimina únicamente la componente DC restando el valor medio. No se aplica filtrado adicional.
"""

def plot_emg(nombre_archivo, titulo):
    emg = cargar_emg(nombre_archivo)
    N = len(emg)
    tiempo = np.arange(N) / fs

    # Eliminación de componente DC
    emg_centrada = emg - np.mean(emg)

    # Dominio del tiempo
    plt.figure(figsize=(14, 4))
    plt.plot(tiempo, emg_centrada, linewidth=0.7)
    plt.title(titulo)
    plt.xlabel('Tiempo (s)')
    plt.ylabel('Amplitud centrada (ADC)')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # Dominio de la frecuencia
    fft_emg = np.fft.rfft(emg_centrada)
    frecuencia = np.fft.rfftfreq(N, d=1/fs)
    magnitud = (2/N) * np.abs(fft_emg)
    if len(magnitud) > 0:
        magnitud[0] /= 2

    plt.figure(figsize=(14, 4))
    plt.plot(frecuencia, magnitud, linewidth=0.7)
    plt.title('Espectro de frecuencia - ' + titulo)
    plt.xlabel('Frecuencia (Hz)')
    plt.ylabel('Magnitud')
    plt.xlim(0, fs/2)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    print(f'Duración: {N/fs:.1f} s | Muestras: {N} | Frecuencia de muestreo: {fs} Hz')

"""## 4. Bíceps - Kevin"""

plot_emg('biceps kevin.txt', 'Señal EMG - Bíceps (Kevin)')

"""## 5. Tríceps - Kevin"""

plot_emg('triceps kevin.txt', 'Señal EMG - Tríceps (Kevin)')

"""## 6. Tríceps - Leo"""

plot_emg('triceps leo.txt', 'Señal EMG - Tríceps (Leo)')

"""## Interpretación

En el dominio del tiempo, los periodos con mayor variación de amplitud corresponden a una mayor actividad eléctrica muscular registrada por el sensor EMG. Los periodos con menor amplitud representan menor activación o reposo relativo.

El espectro de frecuencia, obtenido mediante la Transformada Rápida de Fourier (FFT), permite observar cómo se distribuye el contenido frecuencial de cada señal. Esta representación complementa el ploteo temporal y facilita la comparación entre las diferentes adquisiciones.
"""